name: debug_utils
description: A professional, testable, and extensible logging utility for Flutter apps.
version: 1.0.1
homepage: https://github.com/rapzaDev/debug-utils-flutter
repository: https://github.com/rapzaDev/debug-utils-flutter
issue_tracker: https://github.com/rapzaDev/debug-utils-flutter/issues
documentation: https://github.com/rapzaDev/debug-utils-flutter/blob/main/README.md

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stack_trace: ^1.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

license: MIT